# -*- coding: utf-8 -*-

from django.urls import path

from .views import account, entry, standing_entry


app_name = 'accounts'
urlpatterns = [
    path('account/', account.ListView.as_view(), name='account_list'),
    path('account/create/', account.CreateView.as_view(),
         name='account_create'),
    path('account/autocomplete/', account.autocomplete,
         name='account_autocomplete'),
    path('account/<slug:slug>/', account.DetailView.as_view(),
         name='account_detail'),
    path('account/<slug:slug>)/charts/categories/', account.charts.categories,
         name='account_chart_categories'),
    path('account/<slug:slug>)/charts/statistics/categories/',
         account.charts.statistics.categories,
         name='account_chart_statistics_categories'),
    path('account/<slug:slug>)/charts/statistics/categories/<int:year>/',
         account.charts.statistics.categories,
         name='account_chart_statistics_categories'),
    path('account/<slug:slug>)/charts/statistics/categories/<int:year>/<int:' +
         'month>/', account.charts.statistics.categories,
         name='account_chart_statistics_categories'),
    path('account/<slug:slug>)/charts/statistics/categories/<int:year>/<int:' +
         'month>/<slug:category>/', account.charts.statistics.categories,
         name='account_chart_statistics_categories'),
    path('account/<slug:slug>)/charts/statistics/tags/',
         account.charts.statistics.tags, name='account_chart_statistics_tags'),
    path('account/<slug:slug>)/charts/statistics/tags/<int:year>/',
         account.charts.statistics.tags, name='account_chart_statistics_tags'),
    path('account/<slug:slug>)/charts/statistics/tags/<int:year>/<int:month>/',
         account.charts.statistics.tags, name='account_chart_statistics_tags'),
    path('account/<slug:slug>)/charts/statistics/tags/<int:year>/<int:month>' +
         '/<slug:tag>/', account.charts.statistics.tags,
         name='account_chart_statistics_tags'),
    path('account/<slug:slug>)/charts/tags/', account.charts.tags,
         name='account_chart_tags'),
    path('account/<slug:slug>/edit/', account.UpdateView.as_view(),
         name='account_edit'),
    path('account/<slug:slug>/close/', account.CloseView.as_view(),
         name='account_close'),
    path('account/<slug:slug>/delete/', account.DeleteView.as_view(),
         name='account_delete'),
    path('account/<slug:slug>/entries/', entry.ListView.as_view(),
         name='account_entry_list'),
    path('account/<slug:slug>/entries/<int:page>/', entry.ListView.as_view()),
    path('account/<slug:slug>/entry/add/', entry.CreateView.as_view(),
         name='account_entry_create'),
    path('account/<slug:slug>/entry/standing/add/',
         standing_entry.CreateView.as_view(),
         name='account_standing_entry_create'),
    path('account/<slug:slug>/entry/<int:pk>/',
         entry.DetailView.as_view(), name='account_entry_detail'),
    path('account/<slug:slug>/entry/<int:pk>/edit/',
         entry.UpdateView.as_view(), name='account_entry_edit'),
    path('account/<slug:slug>/entry/<int:pk>/delete/',
         entry.DeleteView.as_view(), name='account_entry_delete'),
    path('account/<slug:slug>/entry/<int:pk>/duplicate/',
         entry.DuplicateView.as_view(), name='account_entry_duplicate'),
    path('account/<slug:slug>/entry/<int:pk>/swap/<str:direction>/',
         entry.SwapView.as_view(), name='account_entry_swap'),
    path('account/<slug:slug>/statements/', account.DetailView.as_view(),
         name='account_statement_list'),
    path('account/<slug:slug>/statistics/', account.StatisticsView.as_view(),
         name='account_statistics'),
    path('account/<slug:slug>/statistics/<str:chart>/',
         account.StatisticsView.as_view(), name='account_statistics'),
    path('account/<slug:slug>/statistics/<str:chart>/<int:year>/',
         account.StatisticsView.as_view(), name='account_statistics'),
    path('account/<slug:slug>/statistics/<str:chart>/<int:year>/<int:month>/',
         account.StatisticsView.as_view(), name='account_statistics'),
    path('account/<slug:slug>/statistics/<str:chart>/<int:year>/<int:month>/' +
         '<slug:obj>/', account.StatisticsView.as_view(),
         name='account_statistics'),

    path('entry/', entry.ListView.as_view(), name='entry_list'),
    path('entry/add/', entry.CreateView.as_view(), name='entry_create'),
    path('entry/standing/add/', standing_entry.CreateView.as_view(),
         name='standing_entry_create'),
    path('entry/<int:pk>/', entry.DetailView.as_view(),
         name='entry_detail'),
    path('entry/<int:pk>/edit/', entry.UpdateView.as_view(),
         name='entry_edit'),
    path('entry/<int:pk>/delete/', entry.DeleteView.as_view(),
         name='entry_delete'),
    path('entry/<int:pk>/duplicate/', entry.DuplicateView.as_view(),
         name='entry_duplicate'),
    path('entry/<int:pk>/swap/<str:direction>/', entry.SwapView.as_view(),
         name='entry_swap'),
]
