# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 15:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0002_tag'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumption_tags', models.ManyToManyField(blank=True, related_name='consumption_tags', to='categories.Tag')),
                ('income_tags', models.ManyToManyField(blank=True, related_name='income_tags', to='categories.Tag')),
                ('insurance_tags', models.ManyToManyField(blank=True, related_name='insurance_tags', to='categories.Tag')),
                ('savings_tags', models.ManyToManyField(blank=True, related_name='savings_tags', to='categories.Tag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': ' budgets',
                'verbose_name': ' budget',
                'ordering': ('user',),
            },
        ),
    ]
