# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import ledger.fields
import units.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('slug', models.SlugField(max_length=2048, unique=True, verbose_name='Slug')),
                ('name', ledger.fields.SingleLineTextField(unique=True, verbose_name='Name')),
                ('symbol', ledger.fields.SingleLineTextField(unique=True, verbose_name='Symbol')),
                ('precision', models.PositiveIntegerField(default=2, verbose_name='Precision')),
            ],
            options={
                'verbose_name_plural': 'Units',
                'verbose_name': 'Unit',
                'ordering': ('name',),
            },
        ),
    ]
