# -*- coding: utf-8 -*-
# vim: ft=python fileencoding=utf-8 sts=4 sw=4 et:
# Copyright (C) 2014-2021 J. Nathanael Philipp (jnphilipp) <nathanael@philipp.land>
#
# This file is part of ledger.
#
# ledger is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ledger is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ledger.  If not, see <http://www.gnu.org/licenses/>.
# Generated by Django 4.0 on 2022-01-13 18:03

from django.db import migrations


def default_units(apps, schema_editor):
    Unit = apps.get_model("units", "Unit")

    Unit.objects.create(
        slug="aed", code="AED", precision=2, name="United Arab Emirates dirham", symbol="د.إ"
    )
    Unit.objects.create(slug="afn", code="AFN", precision=2, name="Afghan afghani", symbol="؋")
    Unit.objects.create(slug="all", code="ALL", precision=2, name="Albanian lek", symbol="L")
    Unit.objects.create(slug="amd", code="AMD", precision=2, name="Armenian dram", symbol="֏")
    Unit.objects.create(
        slug="ang", code="ANG", precision=2, name="Netherlands Antillean guilder", symbol="ƒ"
    )
    Unit.objects.create(slug="aoa", code="AOA", precision=2, name="Angolan kwanza", symbol="Kz")
    Unit.objects.create(slug="ars", code="ARS", precision=2, name="Argentine peso", symbol="$")
    Unit.objects.create(slug="aud", code="AUD", precision=2, name="Australian dollar", symbol="$")
    Unit.objects.create(slug="awg", code="AWG", precision=2, name="Aruban florin", symbol="ƒ")
    Unit.objects.create(slug="azn", code="AZN", precision=2, name="Azerbaijani manat", symbol="₼")
    Unit.objects.create(
        slug="bam",
        code="BAM",
        precision=2,
        name="Bosnia and Herzegovina convertible mark",
        symbol="KM",
    )
    Unit.objects.create(slug="bbd", code="BBD", precision=2, name="Barbados dollar", symbol="$")
    Unit.objects.create(slug="bdt", code="BDT", precision=2, name="Bangladeshi taka", symbol="৳")
    Unit.objects.create(slug="bgn", code="BGN", precision=2, name="Bulgarian lev", symbol="лв.")
    Unit.objects.create(slug="bhd", code="BHD", precision=3, name="Bahraini dinar", symbol=".د.ب")
    Unit.objects.create(slug="bif", code="BIF", precision=0, name="Burundian franc", symbol="Fr")
    Unit.objects.create(slug="bmd", code="BMD", precision=2, name="Bermudian dollar", symbol="$")
    Unit.objects.create(slug="bnd", code="BND", precision=2, name="Brunei dollar", symbol="$")
    Unit.objects.create(slug="bob", code="BOB", precision=2, name="Boliviano", symbol="Bs.")
    Unit.objects.create(slug="brl", code="BRL", precision=2, name="Brazilian real", symbol="R$")
    Unit.objects.create(slug="bsd", code="BSD", precision=2, name="Bahamian dollar", symbol="$")
    Unit.objects.create(
        slug="btn", code="BTN", precision=2, name="Bhutanese ngultrum", symbol="Nu."
    )
    Unit.objects.create(slug="bwp", code="BWP", precision=2, name="Botswana pula", symbol="P")
    Unit.objects.create(slug="byn", code="BYN", precision=2, name="Belarusian ruble", symbol="Br")
    Unit.objects.create(slug="bzd", code="BZD", precision=2, name="Belize dollar", symbol="$")
    Unit.objects.create(slug="cad", code="CAD", precision=2, name="Canadian dollar", symbol="$")
    Unit.objects.create(slug="cdf", code="CDF", precision=2, name="Congolese franc", symbol="Fr")
    Unit.objects.create(slug="chf", code="CHF", precision=2, name="Swiss franc", symbol="Fr.")
    Unit.objects.create(slug="clp", code="CLP", precision=0, name="Chilean peso", symbol="$")
    Unit.objects.create(slug="cny", code="CNY", precision=2, name="Chinese yuan", symbol="元")
    Unit.objects.create(slug="cop", code="COP", precision=2, name="Colombian peso", symbol="$")
    Unit.objects.create(slug="crc", code="CRC", precision=2, name="Costa Rican colon", symbol="₡")
    Unit.objects.create(slug="cup", code="CUP", precision=2, name="Cuban peso", symbol="$")
    Unit.objects.create(slug="cve", code="CVE", precision=2, name="Cape Verdean escudo", symbol="$")
    Unit.objects.create(slug="czk", code="CZK", precision=2, name="Czech koruna", symbol="Kč")
    Unit.objects.create(slug="djf", code="DJF", precision=0, name="Djiboutian franc", symbol="Fr")
    Unit.objects.create(slug="dkk", code="DKK", precision=2, name="Danish krone", symbol="kr")
    Unit.objects.create(slug="dop", code="DOP", precision=2, name="Dominican peso", symbol="RD$")
    Unit.objects.create(slug="dzd", code="DZD", precision=2, name="Algerian dinar", symbol="د.ج")
    Unit.objects.create(slug="egp", code="EGP", precision=2, name="Egyptian pound", symbol="£")
    Unit.objects.create(slug="ern", code="ERN", precision=2, name="Eritrean nakfa", symbol="Nfk")
    Unit.objects.create(slug="etb", code="ETB", precision=2, name="Ethiopian birr", symbol="Br")
    Unit.objects.create(slug="eur", code="EUR", precision=2, name="Euro", symbol="€")
    Unit.objects.create(slug="fjd", code="FJD", precision=2, name="Fiji dollar", symbol="$")
    Unit.objects.create(
        slug="fkp", code="FKP", precision=2, name="Falkland Islands pound", symbol="£"
    )
    Unit.objects.create(slug="gbp", code="GBP", precision=2, name="Pound sterling", symbol="£")
    Unit.objects.create(slug="gel", code="GEL", precision=2, name="Georgian lari", symbol="₾")
    Unit.objects.create(slug="ghs", code="GHS", precision=2, name="Ghanaian cedi", symbol="₵")
    Unit.objects.create(slug="gip", code="GIP", precision=2, name="Gibraltar pound", symbol="£")
    Unit.objects.create(slug="gmd", code="GMD", precision=2, name="Gambian dalasi", symbol="D")
    Unit.objects.create(slug="gnf", code="GNF", precision=0, name="Guinean franc", symbol="Fr")
    Unit.objects.create(slug="gtq", code="GTQ", precision=2, name="Guatemalan quetzal", symbol="Q")
    Unit.objects.create(slug="gyd", code="GYD", precision=2, name="Guyanese dollar", symbol="$")
    Unit.objects.create(slug="hkd", code="HKD", precision=2, name="Hong Kong dollar", symbol="$")
    Unit.objects.create(slug="hnl", code="HNL", precision=2, name="Honduran lempira", symbol="L")
    Unit.objects.create(slug="hrk", code="HRK", precision=2, name="Croatian kuna", symbol="kn")
    Unit.objects.create(slug="htg", code="HTG", precision=2, name="Haitian gourde", symbol="G")
    Unit.objects.create(slug="huf", code="HUF", precision=2, name="Hungarian forint", symbol="Ft")
    Unit.objects.create(slug="idr", code="IDR", precision=2, name="Indonesian rupiah", symbol="Rp")
    Unit.objects.create(slug="ils", code="ILS", precision=2, name="Israeli new shekel", symbol="₪")
    Unit.objects.create(slug="inr", code="INR", precision=2, name="Indian rupee", symbol="₹")
    Unit.objects.create(slug="iqd", code="IQD", precision=3, name="Iraqi dinar", symbol="ع.د")
    Unit.objects.create(slug="irr", code="IRR", precision=2, name="Iranian rial", symbol="﷼")
    Unit.objects.create(slug="isk", code="ISK", precision=0, name="Icelandic króna", symbol="kr")
    Unit.objects.create(slug="jmd", code="JMD", precision=2, name="Jamaican dollar", symbol="$")
    Unit.objects.create(slug="jod", code="JOD", precision=3, name="Jordanian dinar", symbol="د.ا")
    Unit.objects.create(slug="jpy", code="JPY", precision=0, name="Japanese yen", symbol="¥")
    Unit.objects.create(slug="kes", code="KES", precision=2, name="Kenyan shilling", symbol="Sh")
    Unit.objects.create(slug="kgs", code="KGS", precision=2, name="Kyrgyzstani som", symbol="с")
    Unit.objects.create(slug="khr", code="KHR", precision=2, name="Cambodian riel", symbol="៛")
    Unit.objects.create(slug="kmf", code="KMF", precision=0, name="Comoro franc", symbol="Fr")
    Unit.objects.create(slug="kpw", code="KPW", precision=2, name="North Korean won", symbol="₩")
    Unit.objects.create(slug="krw", code="KRW", precision=0, name="South Korean won", symbol="₩")
    Unit.objects.create(slug="kwd", code="KWD", precision=3, name="Kuwaiti dinar", symbol="د.ك")
    Unit.objects.create(
        slug="kyd", code="KYD", precision=2, name="Cayman Islands dollar", symbol="$"
    )
    Unit.objects.create(slug="kzt", code="KZT", precision=2, name="Kazakhstani tenge", symbol="₸")
    Unit.objects.create(slug="lak", code="LAK", precision=2, name="Lao kip", symbol="₭")
    Unit.objects.create(slug="lbp", code="LBP", precision=2, name="Lebanese pound", symbol="ل.ل")
    Unit.objects.create(slug="lkr", code="LKR", precision=2, name="Sri Lankan rupee", symbol="රු")
    Unit.objects.create(slug="lrd", code="LRD", precision=2, name="Liberian dollar", symbol="$")
    Unit.objects.create(slug="lsl", code="LSL", precision=2, name="Lesotho loti", symbol="L")
    Unit.objects.create(slug="lyd", code="LYD", precision=3, name="Libyan dinar", symbol="ل.د")
    Unit.objects.create(slug="mad", code="MAD", precision=2, name="Moroccan dirham", symbol="د.م.")
    Unit.objects.create(slug="mdl", code="MDL", precision=2, name="Moldovan leu", symbol="L")
    Unit.objects.create(slug="mga", code="MGA", precision=2, name="Malagasy ariary", symbol="Ar")
    Unit.objects.create(slug="mkd", code="MKD", precision=2, name="Macedonian denar", symbol="ден")
    Unit.objects.create(slug="mmk", code="MMK", precision=2, name="Myanmar kyat", symbol="Ks")
    Unit.objects.create(slug="mnt", code="MNT", precision=2, name="Mongolian tögrög", symbol="₮")
    Unit.objects.create(slug="mop", code="MOP", precision=2, name="Macanese pataca", symbol="MOP$")
    Unit.objects.create(
        slug="mru", code="MRU", precision=2, name="Mauritanian ouguiya", symbol="UM"
    )
    Unit.objects.create(slug="mur", code="MUR", precision=2, name="Mauritian rupee", symbol="₨")
    Unit.objects.create(slug="mvr", code="MVR", precision=2, name="Maldivian rufiyaa", symbol=".ރ")
    Unit.objects.create(slug="mwk", code="MWK", precision=2, name="Malawian kwacha", symbol="MK")
    Unit.objects.create(slug="mxn", code="MXN", precision=2, name="Mexican peso", symbol="$")
    Unit.objects.create(slug="myr", code="MYR", precision=2, name="Malaysian ringgit", symbol="RM")
    Unit.objects.create(slug="mzn", code="MZN", precision=2, name="Mozambican metical", symbol="MT")
    Unit.objects.create(slug="nad", code="NAD", precision=2, name="Namibian dollar", symbol="$")
    Unit.objects.create(slug="ngn", code="NGN", precision=2, name="Nigerian naira", symbol="₦")
    Unit.objects.create(slug="nio", code="NIO", precision=2, name="Nicaraguan córdoba", symbol="C$")
    Unit.objects.create(slug="nok", code="NOK", precision=2, name="Norwegian krone", symbol="kr")
    Unit.objects.create(slug="npr", code="NPR", precision=2, name="Nepalese rupee", symbol="रू")
    Unit.objects.create(slug="nzd", code="NZD", precision=2, name="New Zealand dollar", symbol="$")
    Unit.objects.create(slug="omr", code="OMR", precision=3, name="Omani rial", symbol="ر.ع.")
    Unit.objects.create(slug="pab", code="PAB", precision=2, name="Panamanian balboa", symbol="B/.")
    Unit.objects.create(slug="pen", code="PEN", precision=2, name="Peruvian sol", symbol="S/.")
    Unit.objects.create(
        slug="pgk", code="PGK", precision=2, name="Papua New Guinean kina", symbol="K"
    )
    Unit.objects.create(slug="php", code="PHP", precision=2, name="Philippine peso", symbol="₱")
    Unit.objects.create(slug="pkr", code="PKR", precision=2, name="Pakistani rupee", symbol="₨")
    Unit.objects.create(slug="pln", code="PLN", precision=2, name="Polish złoty", symbol="zł")
    Unit.objects.create(slug="pyg", code="PYG", precision=0, name="Paraguayan guaraní", symbol="₲")
    Unit.objects.create(slug="qar", code="QAR", precision=2, name="Qatari riyal", symbol="ر.ق")
    Unit.objects.create(slug="ron", code="RON", precision=2, name="Romanian leu", symbol="lei")
    Unit.objects.create(slug="rsd", code="RSD", precision=2, name="Serbian dinar", symbol="дин")
    Unit.objects.create(slug="rub", code="RUB", precision=2, name="Russian ruble", symbol="₽")
    Unit.objects.create(slug="rwf", code="RWF", precision=0, name="Rwandan franc", symbol="Fr")
    Unit.objects.create(slug="sar", code="SAR", precision=2, name="Saudi riyal", symbol="﷼")
    Unit.objects.create(
        slug="sbd", code="SBD", precision=2, name="Solomon Islands dollar", symbol="$"
    )
    Unit.objects.create(slug="scr", code="SCR", precision=2, name="Seychelles rupee", symbol="₨")
    Unit.objects.create(slug="sdg", code="SDG", precision=2, name="Sudanese pound", symbol="ج.س")
    Unit.objects.create(slug="sek", code="SEK", precision=2, name="Swedish krona", symbol="kr")
    Unit.objects.create(slug="sgd", code="SGD", precision=2, name="Singapore dollar", symbol="$")
    Unit.objects.create(slug="shp", code="SHP", precision=2, name="Saint Helena pound", symbol="£")
    Unit.objects.create(
        slug="sll", code="SLL", precision=2, name="Sierra Leonean leone", symbol="Le"
    )
    Unit.objects.create(slug="sos", code="SOS", precision=2, name="Somali shilling", symbol="Sh")
    Unit.objects.create(slug="srd", code="SRD", precision=2, name="Surinamese dollar", symbol="$")
    Unit.objects.create(
        slug="ssp", code="SSP", precision=2, name="South Sudanese pound", symbol="£"
    )
    Unit.objects.create(
        slug="stn", code="STN", precision=2, name="São Tomé and Príncipe dobra", symbol="Db"
    )
    Unit.objects.create(slug="svc", code="SVC", precision=2, name="Salvadoran colón", symbol="₡")
    Unit.objects.create(slug="syp", code="SYP", precision=2, name="Syrian pound", symbol="£S")
    Unit.objects.create(slug="szl", code="SZL", precision=2, name="Swazi lilangeni", symbol="L")
    Unit.objects.create(slug="thb", code="THB", precision=2, name="Thai baht", symbol="฿")
    Unit.objects.create(slug="tjs", code="TJS", precision=2, name="Tajikistani somoni", symbol="с.")
    Unit.objects.create(slug="tmt", code="TMT", precision=2, name="Turkmenistan manat", symbol="m.")
    Unit.objects.create(slug="tnd", code="TND", precision=3, name="Tunisian dinar", symbol="د.ت")
    Unit.objects.create(slug="top", code="TOP", precision=2, name="Tongan paʻanga", symbol="T$")
    Unit.objects.create(slug="try", code="TRY", precision=2, name="Turkish lira", symbol="₺")
    Unit.objects.create(
        slug="ttd", code="TTD", precision=2, name="Trinidad and Tobago dollar", symbol="$"
    )
    Unit.objects.create(slug="twd", code="TWD", precision=2, name="New Taiwan dollar", symbol="$")
    Unit.objects.create(slug="tzs", code="TZS", precision=2, name="Tanzanian shilling", symbol="Sh")
    Unit.objects.create(slug="uah", code="UAH", precision=2, name="Ukrainian hryvnia", symbol="₴")
    Unit.objects.create(slug="ugx", code="UGX", precision=0, name="Ugandan shilling", symbol="USh")
    Unit.objects.create(
        slug="usd", code="USD", precision=2, name="United States dollar", symbol="$"
    )
    Unit.objects.create(slug="uyu", code="UYU", precision=2, name="Uruguayan peso", symbol="$")
    Unit.objects.create(slug="uzs", code="UZS", precision=2, name="Uzbekistan som", symbol="Sʻ")
    Unit.objects.create(slug="vnd", code="VND", precision=0, name="Vietnamese đồng", symbol="₫")
    Unit.objects.create(slug="vuv", code="VUV", precision=0, name="Vanuatu vatu", symbol="Vt")
    Unit.objects.create(slug="wst", code="WST", precision=2, name="Samoan tala", symbol="T")
    Unit.objects.create(slug="yer", code="YER", precision=2, name="Yemeni rial", symbol="﷼")
    Unit.objects.create(slug="zar", code="ZAR", precision=2, name="South African rand", symbol="R")
    Unit.objects.create(slug="zmw", code="ZMW", precision=2, name="Zambian kwacha", symbol="ZK")
    Unit.objects.create(slug="zwl", code="ZWL", precision=2, name="Zimbabwean dollar", symbol="$")
    Unit.objects.create(slug="bch", code="BCH", precision=8, name="Bitcoin Cash", symbol="BCH")
    Unit.objects.create(slug="btc", code="BTC", precision=8, name="Bitcoin", symbol="₿")
    Unit.objects.create(slug="eth", code="ETH", precision=18, name="Ethereum", symbol="Ξ")
    Unit.objects.create(slug="ltc", code="LTC", precision=8, name="Litecoin", symbol="Ł")
    Unit.objects.create(slug="vtc", code="VTC", precision=8, name="Vertcoin", symbol="VTC")
    Unit.objects.create(slug="xlm", code="XLM", precision=8, name="Stellar Lumen", symbol="XLM")
    Unit.objects.create(slug="xmr", code="XMR", precision=12, name="Monero", symbol="XMR")
    Unit.objects.create(slug="xno", code="XNO", precision=30, name="Nano", symbol="Nano")
    Unit.objects.create(slug="xrp", code="XRP", precision=6, name="Ripple", symbol="XRP")
    Unit.objects.create(slug="zec", code="ZEC", precision=8, name="Zcash", symbol="ZEC")
    Unit.objects.create(slug="ozt", code="OZT", precision=4, name="Troy ounce", symbol="oz.tr.")


class Migration(migrations.Migration):

    dependencies = [
        ("units", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(default_units),
    ]
