# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 23:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def add_budgets(apps, schema_editor):
    Ledger = apps.get_model('app', 'Ledger')
    Budget = apps.get_model('app', 'Budget')
    for ledger in Ledger.objects.all():
        Budget.objects.create(user=ledger.user)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_unit_precision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumption_tags', models.ManyToManyField(blank=True, related_name='consumption_tags', to='accounts.Tag')),
                ('income_tags', models.ManyToManyField(blank=True, related_name='income_tags', to='accounts.Tag')),
                ('insurance_tags', models.ManyToManyField(blank=True, related_name='insurance_tags', to='accounts.Tag')),
                ('savings_tags', models.ManyToManyField(blank=True, related_name='savings_tags', to='accounts.Tag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user',),
            },
        ),
        migrations.RunPython(add_budgets),
    ]
