# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ledgers',
            field=models.ManyToManyField(to='users.Ledger', verbose_name='Ledgers'),
        ),
    ]
