# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 21:21
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_tag'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('serial_number', models.IntegerField()),
                ('day', models.DateField()),
                ('amount', models.FloatField(default=0)),
                ('additional', accounts.models.TextFieldSingleLine(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='accounts.Account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='categories.Category')),
                ('tags', models.ManyToManyField(blank=True, related_name='entries', to='categories.Tag')),
            ],
            options={
                'verbose_name_plural': ' entries',
                'ordering': ('account', 'serial_number'),
                'verbose_name': ' entry',
            },
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set([('account', 'serial_number')]),
        ),
    ]
