# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('accounts', '0002_auto_20160601_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ledgers',
            field=models.ManyToManyField(to='users.Ledger'),
        ),
    ]
