# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 07:27
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_tag'),
        ('accounts', '0002_account_ledgers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('serial_number', models.IntegerField(verbose_name='Serial number')),
                ('day', models.DateField(verbose_name='Day')),
                ('amount', models.FloatField(default=0, verbose_name='Amount')),
                ('additional', accounts.models.TextFieldSingleLine(blank=True, null=True, verbose_name='Additional')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='accounts.Account', verbose_name='Account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='categories.Category', verbose_name='Category')),
                ('tags', models.ManyToManyField(blank=True, related_name='entries', to='categories.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'Entries',
                'ordering': ('account', 'serial_number'),
                'verbose_name': 'Entry',
            },
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set([('account', 'serial_number')]),
        ),
    ]
