# -*- coding: utf-8 -*-
# vim: ft=python fileencoding=utf-8 sts=4 sw=4 et:
# Copyright (C) 2014-2021 J. Nathanael Philipp (jnphilipp) <nathanael@philipp.land>
#
# This file is part of ledger.
#
# ledger is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ledger is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ledger.  If not, see <http://www.gnu.org/licenses/>.
# Generated by Django 1.11.1 on 2017-06-27 07:27
from __future__ import unicode_literals

import accounts.models
import ledger.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_tag'),
        ('accounts', '0002_account_ledgers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('serial_number', models.IntegerField(verbose_name='Serial number')),
                ('day', models.DateField(verbose_name='Day')),
                ('amount', models.FloatField(default=0, verbose_name='Amount')),
                ('additional', ledger.fields.SingleLineTextField(blank=True, null=True, verbose_name='Additional')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='accounts.Account', verbose_name='Account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='categories.Category', verbose_name='Category')),
                ('tags', models.ManyToManyField(blank=True, related_name='entries', to='categories.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'Entries',
                'ordering': ('account', 'serial_number'),
                'verbose_name': 'Entry',
            },
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set([('account', 'serial_number')]),
        ),
    ]
