# Generated by Django 4.0 on 2022-01-13 09:38

from django.db import migrations
import ledger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='short_name',
            field=ledger.fields.SingleLineTextField(blank=True, null=True, verbose_name='Short name'),
        ),
    ]
