# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import ledger.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', ledger.fields.TextFieldSingleLine(unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
                'verbose_name': 'Category',
            },
        ),
    ]
