# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 20:54
from __future__ import unicode_literals

import categories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', categories.models.TextFieldSingleLine(unique=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': ' tags',
                'verbose_name': ' tag',
            },
        ),
    ]
