# Generated by Django 2.2.8 on 2020-01-04 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import files.models
import ledger.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_entry_fees'),
        ('files', '0003_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='Created at')),
                ('updated_at', models.DateTimeField(verbose_name='Updated at')),
                ('slug', models.SlugField(max_length=1024, unique=True, verbose_name='Slug')),
                ('name', ledger.fields.SingleLineTextField(verbose_name='Name')),
                ('file', models.FileField(max_length=4096, upload_to=files.models.get_file_path, verbose_name='File')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='accounts.Account', verbose_name='Account')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Statement',
                'verbose_name_plural': 'Statements',
            },
        ),
        migrations.AlterUniqueTogether(
            name='statement',
            unique_together=set([('account', 'name')]),
        ),
    ]
