# Generated by Django 2.2.8 on 2020-01-04 12:40

from django.contrib.contenttypes.models import ContentType
from django.db import migrations
from django.template.defaultfilters import slugify


def migrate_files(apps, schema_editor):
    File = apps.get_model('files', 'OldFile')
    Invoice = apps.get_model('files', 'Invoice')
    Statement = apps.get_model('files', 'Statement')

    Account = apps.get_model('accounts', 'Account')
    account_type = ContentType.objects.get_for_model(Account)
    Entry = apps.get_model('accounts', 'Entry')
    entry_type = ContentType.objects.get_for_model(Entry)
    for file in File.objects.all():
        if file.content_type_id == account_type.pk:
            account = Account.objects.get(pk=file.object_id)
            slug = slugify(f'{account.pk} {file.name}')
            Statement.objects.create(name=file.name, file=file.file, slug=slug,
                                     uploader=file.uploader, account=account,
                                     created_at=file.created_at,
                                     updated_at=file.updated_at)
        elif file.content_type_id == entry_type.pk:
            entry = Entry.objects.get(pk=file.object_id)
            slug = slugify(f'{entry.account.pk} {entry.pk} {file.name}')
            Invoice.objects.create(name=file.name, file=file.file, entry=entry,
                                   uploader=file.uploader, slug=slug,
                                   created_at=file.created_at,
                                   updated_at=file.updated_at)
        file.delete()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('files', '0004_statement'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0004_entry_fees'),
    ]

    operations = [
        migrations.RunPython(migrate_files),
    ]
