# -*- coding: utf-8 -*-
# vim: ft=python fileencoding=utf-8 sts=4 sw=4 et:
# Copyright (C) 2014-2022 J. Nathanael Philipp (jnphilipp) <nathanael@philipp.land>
#
# This file is part of ledger.
#
# ledger is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ledger is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ledger.  If not, see <http://www.gnu.org/licenses/>.
# Generated by Django 4.0 on 2022-01-13 18:03

from django.db import migrations


def default_units(apps, schema_editor):
    Unit = apps.get_model("units", "Unit")

    Unit.objects.create(
        code="AED", precision=2, name="United Arab Emirates dirham", symbol="د.إ"
    )
    Unit.objects.create(code="AFN", precision=2, name="Afghan afghani", symbol="؋")
    Unit.objects.create(code="ALL", precision=2, name="Albanian lek", symbol="L")
    Unit.objects.create(code="AMD", precision=2, name="Armenian dram", symbol="֏")
    Unit.objects.create(
        code="ANG", precision=2, name="Netherlands Antillean guilder", symbol="ƒ"
    )
    Unit.objects.create(code="AOA", precision=2, name="Angolan kwanza", symbol="Kz")
    Unit.objects.create(code="ARS", precision=2, name="Argentine peso", symbol="$")
    Unit.objects.create(code="AUD", precision=2, name="Australian dollar", symbol="$")
    Unit.objects.create(code="AWG", precision=2, name="Aruban florin", symbol="ƒ")
    Unit.objects.create(code="AZN", precision=2, name="Azerbaijani manat", symbol="₼")
    Unit.objects.create(

        code="BAM",
        precision=2,
        name="Bosnia and Herzegovina convertible mark",
        symbol="KM",
    )
    Unit.objects.create(code="BBD", precision=2, name="Barbados dollar", symbol="$")
    Unit.objects.create(code="BDT", precision=2, name="Bangladeshi taka", symbol="৳")
    Unit.objects.create(code="BGN", precision=2, name="Bulgarian lev", symbol="лв.")
    Unit.objects.create(code="BHD", precision=3, name="Bahraini dinar", symbol=".د.ب")
    Unit.objects.create(code="BIF", precision=0, name="Burundian franc", symbol="Fr")
    Unit.objects.create(code="BMD", precision=2, name="Bermudian dollar", symbol="$")
    Unit.objects.create(code="BND", precision=2, name="Brunei dollar", symbol="$")
    Unit.objects.create(code="BOB", precision=2, name="Boliviano", symbol="Bs.")
    Unit.objects.create(code="BRL", precision=2, name="Brazilian real", symbol="R$")
    Unit.objects.create(code="BSD", precision=2, name="Bahamian dollar", symbol="$")
    Unit.objects.create(
        code="BTN", precision=2, name="Bhutanese ngultrum", symbol="Nu."
    )
    Unit.objects.create(code="BWP", precision=2, name="Botswana pula", symbol="P")
    Unit.objects.create(code="BYN", precision=2, name="Belarusian ruble", symbol="Br")
    Unit.objects.create(code="BZD", precision=2, name="Belize dollar", symbol="$")
    Unit.objects.create(code="CAD", precision=2, name="Canadian dollar", symbol="$")
    Unit.objects.create(code="CDF", precision=2, name="Congolese franc", symbol="Fr")
    Unit.objects.create(code="CHF", precision=2, name="Swiss franc", symbol="Fr.")
    Unit.objects.create(code="CLP", precision=0, name="Chilean peso", symbol="$")
    Unit.objects.create(code="CNY", precision=2, name="Chinese yuan", symbol="元")
    Unit.objects.create(code="COP", precision=2, name="Colombian peso", symbol="$")
    Unit.objects.create(code="CRC", precision=2, name="Costa Rican colon", symbol="₡")
    Unit.objects.create(code="CUP", precision=2, name="Cuban peso", symbol="$")
    Unit.objects.create(code="CVE", precision=2, name="Cape Verdean escudo", symbol="$")
    Unit.objects.create(code="CZK", precision=2, name="Czech koruna", symbol="Kč")
    Unit.objects.create(code="DJF", precision=0, name="Djiboutian franc", symbol="Fr")
    Unit.objects.create(code="DKK", precision=2, name="Danish krone", symbol="kr")
    Unit.objects.create(code="DOP", precision=2, name="Dominican peso", symbol="RD$")
    Unit.objects.create(code="DZD", precision=2, name="Algerian dinar", symbol="د.ج")
    Unit.objects.create(code="EGP", precision=2, name="Egyptian pound", symbol="£")
    Unit.objects.create(code="ERN", precision=2, name="Eritrean nakfa", symbol="Nfk")
    Unit.objects.create(code="ETB", precision=2, name="Ethiopian birr", symbol="Br")
    Unit.objects.create(code="EUR", precision=2, name="Euro", symbol="€")
    Unit.objects.create(code="FJD", precision=2, name="Fiji dollar", symbol="$")
    Unit.objects.create(
        code="FKP", precision=2, name="Falkland Islands pound", symbol="£"
    )
    Unit.objects.create(code="GBP", precision=2, name="Pound sterling", symbol="£")
    Unit.objects.create(code="GEL", precision=2, name="Georgian lari", symbol="₾")
    Unit.objects.create(code="GHS", precision=2, name="Ghanaian cedi", symbol="₵")
    Unit.objects.create(code="GIP", precision=2, name="Gibraltar pound", symbol="£")
    Unit.objects.create(code="GMD", precision=2, name="Gambian dalasi", symbol="D")
    Unit.objects.create(code="GNF", precision=0, name="Guinean franc", symbol="Fr")
    Unit.objects.create(code="GTQ", precision=2, name="Guatemalan quetzal", symbol="Q")
    Unit.objects.create(code="GYD", precision=2, name="Guyanese dollar", symbol="$")
    Unit.objects.create(code="HKD", precision=2, name="Hong Kong dollar", symbol="$")
    Unit.objects.create(code="HNL", precision=2, name="Honduran lempira", symbol="L")
    Unit.objects.create(code="HRK", precision=2, name="Croatian kuna", symbol="kn")
    Unit.objects.create(code="HTG", precision=2, name="Haitian gourde", symbol="G")
    Unit.objects.create(code="HUF", precision=2, name="Hungarian forint", symbol="Ft")
    Unit.objects.create(code="IDR", precision=2, name="Indonesian rupiah", symbol="Rp")
    Unit.objects.create(code="ILS", precision=2, name="Israeli new shekel", symbol="₪")
    Unit.objects.create(code="INR", precision=2, name="Indian rupee", symbol="₹")
    Unit.objects.create(code="IQD", precision=3, name="Iraqi dinar", symbol="ع.د")
    Unit.objects.create(code="IRR", precision=2, name="Iranian rial", symbol="﷼")
    Unit.objects.create(code="ISK", precision=0, name="Icelandic króna", symbol="kr")
    Unit.objects.create(code="JMD", precision=2, name="Jamaican dollar", symbol="$")
    Unit.objects.create(code="JOD", precision=3, name="Jordanian dinar", symbol="د.ا")
    Unit.objects.create(code="JPY", precision=0, name="Japanese yen", symbol="¥")
    Unit.objects.create(code="KES", precision=2, name="Kenyan shilling", symbol="Sh")
    Unit.objects.create(code="KGS", precision=2, name="Kyrgyzstani som", symbol="с")
    Unit.objects.create(code="KHR", precision=2, name="Cambodian riel", symbol="៛")
    Unit.objects.create(code="KMF", precision=0, name="Comoro franc", symbol="Fr")
    Unit.objects.create(code="KPW", precision=2, name="North Korean won", symbol="₩")
    Unit.objects.create(code="KRW", precision=0, name="South Korean won", symbol="₩")
    Unit.objects.create(code="KWD", precision=3, name="Kuwaiti dinar", symbol="د.ك")
    Unit.objects.create(
        code="KYD", precision=2, name="Cayman Islands dollar", symbol="$"
    )
    Unit.objects.create(code="KZT", precision=2, name="Kazakhstani tenge", symbol="₸")
    Unit.objects.create(code="LAK", precision=2, name="Lao kip", symbol="₭")
    Unit.objects.create(code="LBP", precision=2, name="Lebanese pound", symbol="ل.ل")
    Unit.objects.create(code="LKR", precision=2, name="Sri Lankan rupee", symbol="රු")
    Unit.objects.create(code="LRD", precision=2, name="Liberian dollar", symbol="$")
    Unit.objects.create(code="LSL", precision=2, name="Lesotho loti", symbol="L")
    Unit.objects.create(code="LYD", precision=3, name="Libyan dinar", symbol="ل.د")
    Unit.objects.create(code="MAD", precision=2, name="Moroccan dirham", symbol="د.م.")
    Unit.objects.create(code="MDL", precision=2, name="Moldovan leu", symbol="L")
    Unit.objects.create(code="MGA", precision=2, name="Malagasy ariary", symbol="Ar")
    Unit.objects.create(code="MKD", precision=2, name="Macedonian denar", symbol="ден")
    Unit.objects.create(code="MMK", precision=2, name="Myanmar kyat", symbol="Ks")
    Unit.objects.create(code="MNT", precision=2, name="Mongolian tögrög", symbol="₮")
    Unit.objects.create(code="MOP", precision=2, name="Macanese pataca", symbol="MOP$")
    Unit.objects.create(
        code="MRU", precision=2, name="Mauritanian ouguiya", symbol="UM"
    )
    Unit.objects.create(code="MUR", precision=2, name="Mauritian rupee", symbol="₨")
    Unit.objects.create(code="MVR", precision=2, name="Maldivian rufiyaa", symbol=".ރ")
    Unit.objects.create(code="MWK", precision=2, name="Malawian kwacha", symbol="MK")
    Unit.objects.create(code="MXN", precision=2, name="Mexican peso", symbol="$")
    Unit.objects.create(code="MYR", precision=2, name="Malaysian ringgit", symbol="RM")
    Unit.objects.create(code="MZN", precision=2, name="Mozambican metical", symbol="MT")
    Unit.objects.create(code="NAD", precision=2, name="Namibian dollar", symbol="$")
    Unit.objects.create(code="NGN", precision=2, name="Nigerian naira", symbol="₦")
    Unit.objects.create(code="NIO", precision=2, name="Nicaraguan córdoba", symbol="C$")
    Unit.objects.create(code="NOK", precision=2, name="Norwegian krone", symbol="kr")
    Unit.objects.create(code="NPR", precision=2, name="Nepalese rupee", symbol="रू")
    Unit.objects.create(code="NZD", precision=2, name="New Zealand dollar", symbol="$")
    Unit.objects.create(code="OMR", precision=3, name="Omani rial", symbol="ر.ع.")
    Unit.objects.create(code="PAB", precision=2, name="Panamanian balboa", symbol="B/.")
    Unit.objects.create(code="PEN", precision=2, name="Peruvian sol", symbol="S/.")
    Unit.objects.create(
        code="PGK", precision=2, name="Papua New Guinean kina", symbol="K"
    )
    Unit.objects.create(code="PHP", precision=2, name="Philippine peso", symbol="₱")
    Unit.objects.create(code="PKR", precision=2, name="Pakistani rupee", symbol="₨")
    Unit.objects.create(code="PLN", precision=2, name="Polish złoty", symbol="zł")
    Unit.objects.create(code="PYG", precision=0, name="Paraguayan guaraní", symbol="₲")
    Unit.objects.create(code="QAR", precision=2, name="Qatari riyal", symbol="ر.ق")
    Unit.objects.create(code="RON", precision=2, name="Romanian leu", symbol="lei")
    Unit.objects.create(code="RSD", precision=2, name="Serbian dinar", symbol="дин")
    Unit.objects.create(code="RUB", precision=2, name="Russian ruble", symbol="₽")
    Unit.objects.create(code="RWF", precision=0, name="Rwandan franc", symbol="Fr")
    Unit.objects.create(code="SAR", precision=2, name="Saudi riyal", symbol="﷼")
    Unit.objects.create(
        code="SBD", precision=2, name="Solomon Islands dollar", symbol="$"
    )
    Unit.objects.create(code="SCR", precision=2, name="Seychelles rupee", symbol="₨")
    Unit.objects.create(code="SDG", precision=2, name="Sudanese pound", symbol="ج.س")
    Unit.objects.create(code="SEK", precision=2, name="Swedish krona", symbol="kr")
    Unit.objects.create(code="SGD", precision=2, name="Singapore dollar", symbol="$")
    Unit.objects.create(code="SHP", precision=2, name="Saint Helena pound", symbol="£")
    Unit.objects.create(
        code="SLL", precision=2, name="Sierra Leonean leone", symbol="Le"
    )
    Unit.objects.create(code="SOS", precision=2, name="Somali shilling", symbol="Sh")
    Unit.objects.create(code="SRD", precision=2, name="Surinamese dollar", symbol="$")
    Unit.objects.create(
        code="SSP", precision=2, name="South Sudanese pound", symbol="£"
    )
    Unit.objects.create(
        code="STN", precision=2, name="São Tomé and Príncipe dobra", symbol="Db"
    )
    Unit.objects.create(code="SVC", precision=2, name="Salvadoran colón", symbol="₡")
    Unit.objects.create(code="SYP", precision=2, name="Syrian pound", symbol="£S")
    Unit.objects.create(code="SZL", precision=2, name="Swazi lilangeni", symbol="L")
    Unit.objects.create(code="THB", precision=2, name="Thai baht", symbol="฿")
    Unit.objects.create(code="TJS", precision=2, name="Tajikistani somoni", symbol="с.")
    Unit.objects.create(code="TMT", precision=2, name="Turkmenistan manat", symbol="m.")
    Unit.objects.create(code="TND", precision=3, name="Tunisian dinar", symbol="د.ت")
    Unit.objects.create(code="TOP", precision=2, name="Tongan paʻanga", symbol="T$")
    Unit.objects.create(code="TRY", precision=2, name="Turkish lira", symbol="₺")
    Unit.objects.create(
        code="TTD", precision=2, name="Trinidad and Tobago dollar", symbol="$"
    )
    Unit.objects.create(code="TWD", precision=2, name="New Taiwan dollar", symbol="$")
    Unit.objects.create(code="TZS", precision=2, name="Tanzanian shilling", symbol="Sh")
    Unit.objects.create(code="UAH", precision=2, name="Ukrainian hryvnia", symbol="₴")
    Unit.objects.create(code="UGX", precision=0, name="Ugandan shilling", symbol="USh")
    Unit.objects.create(
        code="USD", precision=2, name="United States dollar", symbol="$"
    )
    Unit.objects.create(code="UYU", precision=2, name="Uruguayan peso", symbol="$")
    Unit.objects.create(code="UZS", precision=2, name="Uzbekistan som", symbol="Sʻ")
    Unit.objects.create(code="VND", precision=0, name="Vietnamese đồng", symbol="₫")
    Unit.objects.create(code="VUV", precision=0, name="Vanuatu vatu", symbol="Vt")
    Unit.objects.create(code="WST", precision=2, name="Samoan tala", symbol="T")
    Unit.objects.create(code="YER", precision=2, name="Yemeni rial", symbol="﷼")
    Unit.objects.create(code="ZAR", precision=2, name="South African rand", symbol="R")
    Unit.objects.create(code="ZMW", precision=2, name="Zambian kwacha", symbol="ZK")
    Unit.objects.create(code="ZWL", precision=2, name="Zimbabwean dollar", symbol="$")
    Unit.objects.create(code="BCH", precision=8, name="Bitcoin Cash", symbol="BCH")
    Unit.objects.create(code="BTC", precision=8, name="Bitcoin", symbol="₿")
    Unit.objects.create(code="ETH", precision=18, name="Ethereum", symbol="Ξ")
    Unit.objects.create(code="LTC", precision=8, name="Litecoin", symbol="Ł")
    Unit.objects.create(code="VTC", precision=8, name="Vertcoin", symbol="VTC")
    Unit.objects.create(code="XLM", precision=8, name="Stellar Lumen", symbol="XLM")
    Unit.objects.create(code="XMR", precision=12, name="Monero", symbol="XMR")
    Unit.objects.create(code="XNO", precision=30, name="Nano", symbol="Nano")
    Unit.objects.create(code="XRP", precision=6, name="Ripple", symbol="XRP")
    Unit.objects.create(code="ZEC", precision=8, name="Zcash", symbol="ZEC")
    Unit.objects.create(code="OZT", precision=4, name="Troy ounce", symbol="oz.tr.")


class Migration(migrations.Migration):

    dependencies = [
        ("units", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(default_units),
    ]
