# -*- coding: utf-8 -*-
# vim: ft=python fileencoding=utf-8 sts=4 sw=4 et:
# Copyright (C) 2014-2022 J. Nathanael Philipp (jnphilipp) <nathanael@philipp.land>
#
# This file is part of ledger.
#
# ledger is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ledger is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ledger.  If not, see <http://www.gnu.org/licenses/>.
# Generated by Django 4.0 on 2022-01-14 09:05

from django.db import migrations, models
import django.db.models.deletion
import ledger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('serial_number', models.IntegerField(verbose_name='Serial number')),
                ('date', models.DateField(verbose_name='Date')),
                ('amount', models.FloatField(default=0., verbose_name='Amount')),
                ('fees', models.FloatField(default=0., verbose_name='Fees')),
                ('text', ledger.fields.SingleLineTextField(blank=True, null=True, verbose_name='Text')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='ledger.account', verbose_name='Account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='ledger.category', verbose_name='Category')),
                ('tags', models.ManyToManyField(blank=True, related_name='entries', to='ledger.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
                'ordering': ('account', 'serial_number'),
                'unique_together': {('account', 'serial_number')},
            },
        ),
    ]
