name: Tests

on: [push, pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
      - uses: psf/black@stable
      - name: Flake8
        run: |
          python -m pip install flake8
          flake8 . --max-line-length=88 --extend-ignore=E203 --extend-exclude="migrations,tests" --count --statistics
      - name: mypy
        run: |
          python -m pip install mypy
          mypy . --ignore-missing-imports --exclude migrations/ --exclude tests
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        django-version: ["3.2", "4.0", "4.1"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
          pip install Django~=${{ matrix.django-version }}
      - name: Run Tests
        run: |
          cd ledger
          python manage.py test
